---
# tasks file for k8s_slave

- name: Install net-tools for network management
  apt:
    name: net-tools
    state: present

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: "Installing Tinc"
  apt: name={{item}} state=present
  with_items:
    - tinc

- name: "Create a directory for tinc configurations"
  shell: mkdir -p /etc/tinc/netname/hosts

- name: "copy tinc.conf file"
  template:
    src: tinc.conf
    dest: "/etc/tinc/netname/"

- name: "Copy hosts config file"
  template:
    src: slave
    dest: "/etc/tinc/netname/hosts/"

- name: "create key pairs"
  shell: tincd -n netname -K4096
  responses:
    'Please enter a file to save private RSA key to [/etc/tinc/netname/rsa_key.priv]: ': ''
    'Please enter a file to save public RSA key to [/etc/tinc/netname/hosts/externalnyc]: ': ''

- name: "copy tinc-up script"
  template:
    src: tinc-up
    dest: "/etc/tinc/netname/"

- name: "copy tinc-down script"
  template:
    src: tinc-down
    dest: "/etc/tinc/netname/"

- name: "Make the tinc scripts executable"
  shell: chmod 755 /etc/tinc/netname/tinc-*

# Adding kubernetes repo from base url using gpg keys
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
 
- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
 
- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

# Installing 'docker', 'kubeadm' and 'iproute-tc' on slave node 
- name: Installing Docker & kubeadm on Slave Node
  package:
    name:
      - kubeadm
      - iproute2
    state: present

# Starting and enabling the docker on master node.
- name: enabling Docker on Master Node
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker registry is available
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

- name: ensure docker and dependencies are installed
  apt: name=docker-ce update_cache=yes
  
# Starting kubelet services on slave node.
- name: Staring & enabling Docker & kubelet on Slave Node
  service:
    name: kubelet
    state: started
    enabled: yes

# Updating Docker cgroup on slave Node. Reason for using cgroupdriver as 'systemd' instead of default ones, 
# https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
- name: Updating Docker cgroup on Slave Node
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

# Restart the docker on slave node to get all things activated
- name: Restart Docker on Slave Node
  service:
    name: docker
    state: restarted

# Updating IP tables on Slave Node. Usually in the linux distros like ubuntu,
# (https://www.kevinhooke.com/2018/11/23/checking-iptables-filtering-for-bridge-networking-on-ubuntu-for-kubernetes-setup/)
# the bridge module in the kernel for "ip6tables, iptables and arptables" has the default set to "1"
# ("on", i.e. "*do* send the packets to iptables"), but for the distros like Fedora, RHEL, and CentOS they are set to '0' so we need to
# update the '/etc/sysctl.d/k8s.conf' to set it to '1'
- name: Updating IP tables on Slave Node
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

# Reloading sysctl on Slave Node to activate the bridge changes
- name: Reloading sysctl on Slave Node
  command: sysctl --system

# Now this is the crucial part, joining our slave nodes to our master node 
# “hostvars[groups[‘ec2_master’][0]]” option is calling the namespace of the master node from ec2 role.
# Next, using “[‘token’][‘stdout’]” we just parse the command that we can use in slave to join the master node
# - name: Joining the master node
#   command: "{{ hostvars[groups['ec2_master'][0]]['token']['stdout'] }}"

# Cleaning caches on nodes RAM's. The “shell” module used here to clean the buffer cache on the slave nodes,
# because while doing the setup it will create lots of temporary data on RAM
- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches