# A script that starts all the roles (ec2 (launching instances), master node and worker nodes)

# Running EC2 Role for lauching instances and assigning them to respective groups
- hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
        - cred.yml
  tasks:
    - name: Running EC2 Role
      include_role:
        name: ec2

#Run vpn server
- hosts: ec2_vpn
  gather_facts: no
  become: yes
  tasks:
    - name: Running K8s VPN Role
      include_role:
        name: k8s_vpn_ovpn

# Running k8s master role with all required installations, updates, appropriate customizations, networking on master node and prepare
# for docking worker nodes to master nodes in later process.
- hosts: ec2_master
  gather_facts: no
  become: yes
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: k8s_master_ovpn

# Running k8s worker role with all required installations, updates, appropriate customizations, networking on worker nodes and dock the
# worker nodes to our master node.
- hosts: ec2_worker
  gather_facts: no
  become: yes
  tasks:
    - name: Running K8s worker Role
      include_role:
        name: k8s_worker_ovpn

- hosts: ec2_test
  gather_facts: no
  become: yes
  tasks:
    - name: Running K8s test machine role
      include_role:
        name: k8s_test_ovpn