---

- name: Install net-tools for network management
  apt:
    name: net-tools
    state: present

- name: Install nginx LB for external access
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Remove default nginx config
  shell: rm -rf /etc/nginx/nginx.conf

- name: Get the vps gateway ip
  shell: "route -n | grep 'UG[ \t]' | awk '{print $2}'"
  register: private_ip

- name: Arrange route for ssh to access via primary interface
  shell: "route add -host 213.112.64.208 gw {{ private_ip.stdout }}"

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Download softether from internet
  shell: wget https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.38-9760-rtm/softether-vpnclient-v4.38-9760-rtm-2021.08.17-linux-x64-64bit.tar.gz
  args:
    chdir: $HOME

- name: Untar the softether vpnclient
  shell: tar xzvf softether-vpnclient-v4.38-9760-rtm-2021.08.17-linux-x64-64bit.tar.gz
  args:
    chdir: $HOME

- name: Download build-essentials packages
  shell: apt-get install build-essential -y

- name: build the softether vpn client
  shell: make
  args:
    chdir: $HOME/vpnclient

- name: Run vpnclient from anywhere
  shell: mv vpnclient/ /usr/local/
  args:
    chdir: $HOME

- name: Set limited permissions to vpnclient and related utilities
  shell: chmod 600 * && chmod 700 vpnclient && chmod 700 vpncmd
  args:
    chdir: /usr/local/vpnclient/

- name: Start the vpnclient
  shell: ./vpnclient start
  args:
    chdir: /usr/local/vpnclient/

# Adding kubernetes repo from base url using gpg keys
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
 
- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
 
- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

# Installing 'docker', 'kubeadm' and 'iproute-tc' on master node 
- name: Installing Docker & kubeadm on Master Node
  package:
    name:
      - kubeadm
      - iproute2
    state: present

# Starting and enabling the docker on master node.
- name: enabling Docker on Master Node
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker registry is available
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

- name: ensure docker and dependencies are installed
  apt: name=docker-ce update_cache=yes

- name: ensure docker-ce-cli installed
  apt: name=docker-ce-cli

- name: ensure containerd.io installed
  apt: name=containerd.io

# Starting kubelet on master node. we maybe have a question on why kubelet is run on master node?
# The reason for running kubelet on master node is that, kubeadm uses containers (pods) to deploy etcd and the api server components. 
# For this, static manifests are created as yaml-files which are picked up by the kubelet on the master node 
# to provide the infrastructure pods. An added benefit is that you have the master node metrics available from the kubernetes api.
- name: Staring kubelet on Master Node
  service:
    name: kubelet
    state: started
    enabled: yes

# Updating Docker cgroup on Master Node. Reason for using cgroupdriver as 'systemd' instead of default ones, 
# https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
- name: Updating Docker cgroup on Master Node
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

# Restart the docker on Master node to get all things activated
- name: Restart docker on Master Node
  service:
    name: docker
    state: restarted

- name: swapp off
  shell: swapoff -a

- name: Workaround for running kube-api server on ubuntu_21.x and later versions
  shell:
    cmd: |
      containerd config default | tee /etc/containerd/config.toml
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      service containerd restart
      service kubelet restart

# copy application to the server
- name: "copy deployments file to master"
  template:
    src: deployments.yml
    dest: "/root/"

# copy services to the server
- name: "copy services file to master"
  template:
    src: services.yml
    dest: "/root/"

# copy steps to follow to the server
- name: "copy services file to master"
  template:
    src: client1.txt
    dest: "/root/"

# copy nginx LB config to the server
- name: "copy nginx file to master"
  template:
    src: nginx.conf
    dest: "/root/"

# Cleaning caches on nodes RAM's. The “shell” module used here to clean the buffer cache on the master node,
# because while doing the setup it will create lots of temporary data on RAM
- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches