---
# tasks file for k8s_master

- name: Copy automated script to test server
  template:
      src: curl_req.sh
      dest: "/root/"

- name: Arrange executable permissions to the curl script
  shell: chmod a+x /root/curl_req.sh