---
# tasks file for k8s_vpn

# Installing wireguard
- name: install wireguard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: generate public and private key
  shell:
    cmd: umask 077 && wg genkey | sudo tee /etc/wireguard/privatekey | wg pubkey | sudo tee /etc/wireguard/publickey

- name: create server wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: roles/k8s_vpn/templates/wg0.conf.j2
    owner: root
    group: root
    mode: '0600'

- name: replace line
  lineinfile: 
    path: /etc/sysctl.conf
    regexp: '^(.*)#net.ipv4.ip_forward=1(.*)$' 
    line: 'net.ipv4.ip_forward=1'
    backrefs: yes

- name: Apply the ip forwarding change
  shell:
    cmd: sysctl -p