---
# tasks file for k8s_master

- name: Copy automated script to test server
  template:
      src: curl_req.sh
      dest: "/root/"

- name: Arrange executable permissions to the curl script
  shell: chmod a+x /root/curl_req.sh

- name: Install net-tools for network management
  apt:
    name: net-tools
    state: present

# copy steps to follow to the server
- name: "copy steps file to test server"
  template:
    src: steps.txt
    dest: "/root/"