apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
    tier: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30008
  selector:
    app: hello
    tier: web